### ISSUE TITLE
PaperTrail 11 support

### ISSUE THREAD

**Issue by matthew-puku** [hintmedia/paper_trail_scrapbook#60]
Heya! We're on the dependency upgrade warpath at the moment. Was wondering if you had plans to support PaperTrail 11.x? [The changes](https://github.com/paper-trail-gem/paper_trail/blob/v11.1.0/CHANGELOG.md) look pretty innocent so I don't think it'd be too traumatic.

Happy to pitch in if you'd like a hand with anything!

**Comment by tjchambers** [comment]
@matthew-puku thanks for this issue and question. We will take a look-see at those changes, but am pretty certain we ourselves will have a need for that compatibility. Always happy to have PR's if you are interested in contributing!

**Comment by matthew-puku** [comment]
Yeah cool. I'll see about having a look this weekend.

**Comment by dinjas** [comment]
Fixed in #61. I'll get a new version of the gem published today.
